name: php checks

on: [push]

jobs:
  stand_alone_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Validate composer.json
      run: composer validate   
    - name: validate php syntax
      run: find . -not -path "./vendor/*" -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
    - name: install phpcs
      run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    - name: phpcs psr12
      run: php phpcs.phar --standard=PSR12 --extensions=php --ignore=vendor .
  tests:
    needs: stand_alone_checks
    strategy:
      matrix:
        tag: [v3_6.1_php7.1, v3_6.1_php7.2, v3_6.2-rc_php7.2, v3_6.2-rc_php7.1, v3_dev-master_php7.2]         
    runs-on: ubuntu-latest
    container:
      image: oxidprojects/oxid-test:${{matrix.tag}}
      options: -v /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
    env:
      DB_HOST: "127.0.0.1"
    steps:
    - uses: actions/checkout@v1
    - name: route db from socket to port
      run: bash /var/www/oxideshop/scripts/routeDbfromSocketToPort.sh            
    - name: setup oxid
      run: bash /var/www/oxideshop/scripts/setupOxid.sh
    - name: install this package into oxid
      run: bash /var/www/oxideshop/scripts/setupPackage.sh
    - name: phpstan
      run: |
        MD=$(pwd)
        cd /var/www/oxideshop
        touch autoload.oxid.php
        cp $MD/phpstan-baseline.neon .
        vendor/bin/phpstan analys --configuration phpstan.neon $MD
      continue-on-error: true
    - name: psalm
      run: |
        MD=$(pwd)
        cd /var/www/oxideshop
        curl -OL https://circleci.com/api/v1.1/project/github/weirdan/psalm/232/artifacts/0/home/docker/project/build/psalm.phar
        php psalm.phar --stats --show-info=true $MD
    - name: debug phpunit class not found
      continue-on-error: true
      run: |
        MD=$(pwd)
        cd /var/www/oxideshop
        composer show phpunit/phpunit
    - name: test with phpunit 8
      continue-on-error: true
      run: |
        MD=$(pwd)
        cd /var/www/oxideshop
        ./phpunit --version
        ./phpunit -vvv --bootstrap source/bootstrap.php ${MD}/src/Tests/ShopSwitcherIteratorTest.php
        echo this will only shown if test run
    - name: test with buildin phpunit
      continue-on-error: true
      run: |
        MD=$(pwd)
        cd /var/www/oxideshop
        vendor/bin/phpunit --version
        vendor/bin/phpunit -vvv --bootstrap source/bootstrap.php ${MD}/src/Tests/ShopSwitcherIteratorTest.php
        echo this will only shown if test run
    - name: test with testing framework
      continue-on-error: true
      run: |
        MD=$(pwd)
        cd /var/www/oxideshop
        vendor/bin/runtests --version
        vendor/bin/runtests -vvv ${MD}/src/Tests/ShopSwitcherIteratorTest.php
        echo this will only shown if test run
    - run: mysql -u root -proot -e "SELECT * FROM oxshops" oxid
      continue-on-error: true
    - name: logs
      run: |
        ls /var/www/oxideshop/source/log
        cat /var/www/oxideshop/source/log/*
      continue-on-error: true

   
